name: Generate rust cache for PR builds
on:
  push

env:
    CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.82.0

    - name: checkout verifier
      uses: actions/checkout@v6
      with:
        path: verifier
        submodules: recursive

    - name: checkout powdr
      uses: actions/checkout@v6
      with:
        repository: Certora/powdr
        ref: develop
        path: powdr
        submodules: recursive
        ssh-key: ${{ secrets.DEPLOY_KEY_POWDR }}

    - name: setup cargo cache
      uses: actions/cache@v3
      with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            powdr/target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-
    
    - name: install python dependencies
      run: |
        pip install -r verifier/requirements.txt
        pysmt-install --z3 --confirm-agreement

    - name: run test case
      run: APC_CBOR_PATH=../../data cargo test single_add_1 -- --no-capture
      working-directory: powdr
    
    - name: deserialize test case
      run: |
        for file in `ls ../data/*.cbor`; do
          cargo run --bin deserialize babybear ${file} human ${file%.cbor}.txt
          cargo run --bin deserialize babybear ${file} json ${file%.cbor}.json
        done
      working-directory: powdr
    
    - name: run tracer
      run: |
        for file in `ls data/apc_*.json`; do
          python3 verifier/main.py trace ${file}
        done
    