name: Generate rust cache for PR builds
on:
  push

env:
    CARGO_TERM_COLOR: always
    TEST_CASES: single_add_1 single_loadbu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.82.0

    - name: checkout verifier
      uses: actions/checkout@v6
      with:
        path: verifier
        submodules: recursive

    - name: checkout powdr
      uses: actions/checkout@v6
      with:
        repository: Certora/powdr
        ref: develop
        path: powdr
        submodules: recursive
        ssh-key: ${{ secrets.DEPLOY_KEY_POWDR }}
    
    - name: get date for cache key
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash

    - name: setup cargo cache
      uses: actions/cache@v3
      with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            powdr/target/
          key: cargo-${{ hashFiles('powdr/Cargo.toml') }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            cargo-
    
    - name: install python dependencies
      run: |
        pip install -r verifier/requirements.txt
        pysmt-install --z3 --confirm-agreement

    - name: cargo clean
      run: cd powdr && cargo clean

    - name: run test cases
      run: |
        for test in ${{ env.TEST_CASES }}; do
          echo "::group::run powdr on ${test}"
          python3 verifier/orchestrate.py powdr ${test} || exit 1
          echo "::endgroup::"
        done
    
    - name: run tracer
      run: |
        for test in ${{ env.TEST_CASES }}; do
          echo "::group::run tracer on ${test}"
          python3 verifier/orchestrate.py trace-all ${test} || exit 1
          echo "::endgroup::"
        done
    
    - name: run evaluator
      run: |
        for test in ${{ env.TEST_CASES }}; do
          echo "::group::run evaluator on ${test}"
          python3 verifier/orchestrate.py eval-all ${test} || exit 1
          echo "::endgroup::"
        done
    
    - name: run separate evaluator
      run: |
        for test in ${{ env.TEST_CASES }}; do
          echo "::group::run separate evaluator on ${test}"
          python3 verifier/orchestrate.py evaluate-all ${test} || exit 1
          echo "::endgroup::"
        done

    - name: run verifier
      run: |
        for test in ${{ env.TEST_CASES }}; do
          echo "::group::run verifier on ${test}"
          python3 verifier/orchestrate.py verify-stepwise ${test} || exit 1
          echo "::endgroup::"
        done
    