from enum import Enum
import itertools
import logging
from typing import Any

from .single_interaction_encoder import SingleInteractionEncoder
from . import openvm_bitwise_lookup
from . import openvm_execution_bridge
from . import openvm_memory
from . import openvm_pc_lookup
from . import openvm_variable_range_checker
from . import openvm_tuple_range_checker

from ..smt.utils import *
from ..utils.basic_block import BasicBlock
from ..utils.utils import merge_dicts


class InteractionEncoder:
    """Base class for an encoder of arbitrary bus interactions."""

    def __init__(self, encoders: list[SingleInteractionEncoder], cur_state: Any):
        """
        Initialize with the list of encoders. The order in this list fixes the
        order in which the encoders are applied.
        """
        self.encoders = encoders
        for e in encoders:
            setattr(e, "_cur_state", cur_state)

    def add(self, data: Any):
        """Dispatch a single interaction record to the appropriate per-bus encoder."""
        raise NotImplementedError

    def add_all(self, data: Iterable[Any]):
        """Add all interactions from an iterable by repeatedly calling `add`."""
        for d in data:
            self.add(d)

    def encode_all(self) -> list[FNode]:
        """Encode all accumulated interactions across all sub-encoders."""
        return list(
            without_trues(
                itertools.chain.from_iterable(
                    encoder.encode_all() for encoder in self.encoders
                )
            )
        )

    def get_axioms(self) -> list[FNode]:
        """Return axioms generated by sub-encoders."""
        return list(without_trues(encoder.get_axioms() for encoder in self.encoders))

    def get_globals(self) -> frozenset[FNode]:
        """Returns all global symbols that should not be part of any quantifier"""
        return frozenset.union(*[encoder.get_globals() for encoder in self.encoders])

    def get_interpreters(self) -> dict[FNode, FunctionInterpretation]:
        """Returns interpreters for all UFs for evaluation."""
        return merge_dicts(
            self.encoders, lambda encoder: getattr(encoder, "interpreters", {})
        )

    def get_inputs(self) -> dict:
        """Return a dict describing per-bus input symbols used by the encoding."""
        return merge_dicts(self.encoders, lambda encoder: encoder.get_inputs())

    def get_outputs(self) -> dict:
        """Return a dict describing per-bus output symbols produced by the encoding."""
        return merge_dicts(self.encoders, lambda encoder: encoder.get_outputs())

    def get_auxiliaries(self) -> frozenset[FNode]:
        """Return auxiliary symbols introduced by the encoding."""
        return frozenset.union(
            *[encoder.get_auxiliaries() for encoder in self.encoders]
        )


class OpenVMBusInteraction(Enum):
    """Numeric identifiers for the supported OpenVM bus interactions."""

    EXECUTION_BRIDGE = 0
    MEMORY = 1
    PC_LOOKUP = 2
    VARIABLE_RANGE_CHECKER = 3
    BITWISE_LOOKUP = 6
    TUPLE_RANGE_CHECKER = 7

    def __str__(self) -> str:
        """Return the numeric bus id as a string (for logging/rendering)."""
        return str(self.value)


class OpenVMBusInteractionEncoder(InteractionEncoder):
    """Encoder for the OpenVM bus interactions."""

    def __init__(self, basic_block: BasicBlock, cur_state: Any):
        """Create OpenVM sub-encoders and wire them to the current converter state."""
        self.bitwise_lookup = openvm_bitwise_lookup.OpenVMBitwiseLookupEncoder()
        self.execution_bridge = openvm_execution_bridge.OpenVMExecutionBridgeEncoder()
        self.memory = openvm_memory.OpenVMMemoryEncoder()
        self.pc_lookup = openvm_pc_lookup.OpenVMPCLookupEncoder(basic_block)
        self.variable_range_checker = (
            openvm_variable_range_checker.OpenVMVariableRangeCheckerEncoder()
        )
        self.tuple_range_checker = (
            openvm_tuple_range_checker.OpenVMTupleRangeCheckerEncoder()
        )

        super().__init__(
            [
                self.bitwise_lookup,
                self.execution_bridge,
                self.pc_lookup,
                self.variable_range_checker,
                self.tuple_range_checker,
                self.memory,
            ],
            cur_state,
        )

    def add(self, data: Any):
        """Pattern-match a raw bus interaction record and forward it to the right encoder."""
        match data:
            case {
                "id": OpenVMBusInteraction.EXECUTION_BRIDGE.value,
                "mult": mult,
                "args": [pc, timestamp],
            }:
                self.execution_bridge.add(mult, pc, timestamp)
            case {
                "id": OpenVMBusInteraction.MEMORY.value,
                "mult": mult,
                "args": [address_space, pointer, *data, timestamp],
            }:
                self.memory.add(mult, address_space, pointer, data, timestamp)
            case {
                "id": OpenVMBusInteraction.PC_LOOKUP.value,
                "mult": mult,
                "args": [pc, op, a, b, c, d, e, f, g],
            }:
                self.pc_lookup.add(mult, pc, op, a, b, c, d, e, f, g)
            case {
                "id": OpenVMBusInteraction.VARIABLE_RANGE_CHECKER.value,
                "mult": mult,
                "args": [x, bits],
            }:
                self.variable_range_checker.add(mult, x, bits)
            case {
                "id": OpenVMBusInteraction.BITWISE_LOOKUP.value,
                "mult": mult,
                "args": [x, y, z, op],
            }:
                self.bitwise_lookup.add(mult, x, y, z, op)
            case {
                "id": OpenVMBusInteraction.TUPLE_RANGE_CHECKER.value,
                "mult": mult,
                "args": [x, y],
            }:
                self.tuple_range_checker.add(mult, x, y)
            case _:
                logging.error(f"Unsupported bus interaction: {data}")
