from enum import Enum
import itertools
import logging
from typing import Any

from .single_interaction_encoder import SingleInteractionEncoder
from . import openvm_bitwise_lookup
from . import openvm_execution_bridge
from . import openvm_memory
from . import openvm_pc_lookup
from . import openvm_variable_range_checker
from . import openvm_tuple_range_checker

from ..smt.utils import *
from ..utils.basic_block import BasicBlock
from ..utils.utils import merge_dicts


class InteractionEncoder:
    """Base class for an encoder of arbitrary bus interactions."""

    def __init__(self, cur_state: Any):
        self._cur_state = cur_state
        self.encoders = []
    
    def add_encoder(self, encoder: SingleInteractionEncoder):
        self.encoders.append(encoder)
        setattr(encoder, "_cur_state", self._cur_state)

    def verify_bus_ids(self, bus_ids: dict[str, int]):
        """Verify that the bus ids are correct."""
        pass

    def add(self, data: Any):
        """Dispatch a single interaction record to the appropriate per-bus encoder."""
        raise NotImplementedError

    def add_all(self, data: Iterable[Any]):
        """Add all interactions from an iterable by repeatedly calling `add`."""
        for d in data:
            self.add(d)

    def encode(self) -> Iterable[FNode]:
        """Encode all accumulated interactions across all sub-encoders."""
        for encoder in self.encoders:
            yield from encoder.encode()

    def get_axioms(self) -> Iterable[FNode]:
        """Return axioms generated by sub-encoders."""
        for encoder in self.encoders:
            yield from encoder.get_axioms()

    def get_globals(self) -> frozenset[FNode]:
        """Returns all global symbols that should not be part of any quantifier"""
        return frozenset.union(*[encoder.get_globals() for encoder in self.encoders])

    def get_interpreters(self) -> dict[FNode, FunctionInterpretation]:
        """Return interpreters for all UFs for evaluation. The returned
        dictionary maps UF symbols to data that is accepted by the
        `partial_evaluate` function and thus by the `GenericInterpreter`
        class: either a pair of a concrete evaluator and a symbolic
        simplifier, or just a concrete evaluator."""
        return merge_dicts(self.encoders, lambda encoder: encoder.get_interpreters())

    def get_inputs(self) -> dict:
        """Return a dict describing per-bus input symbols used by the encoding."""
        return merge_dicts(self.encoders, lambda encoder: encoder.get_inputs())

    def get_outputs(self) -> dict:
        """Return a dict describing per-bus output symbols produced by the encoding."""
        return merge_dicts(self.encoders, lambda encoder: encoder.get_outputs())

    def get_auxiliaries(self) -> frozenset[FNode]:
        """Return a dict describing per-mus auxiliary symbols introduced by the encoding."""
        return merge_dicts(self.encoders, lambda encoder: encoder.get_auxiliaries())


class OpenVMBusInteraction(Enum):
    """Numeric identifiers for the supported OpenVM bus interactions."""

    EXECUTION_BRIDGE = 0
    MEMORY = 1
    PC_LOOKUP = 2
    VARIABLE_RANGE_CHECKER = 3
    BITWISE_LOOKUP = 6
    TUPLE_RANGE_CHECKER = 7

    def __str__(self) -> str:
        """Return the numeric bus id as a string (for logging/rendering)."""
        return str(self.value)


class OpenVMBusInteractionEncoder(InteractionEncoder):
    """Encoder for the OpenVM bus interactions."""

    def __init__(self, basic_block: BasicBlock, cur_state: Any):
        """Create OpenVM sub-encoders and wire them to the current converter state."""
        self.bitwise_lookup = openvm_bitwise_lookup.OpenVMBitwiseLookupEncoder()
        self.execution_bridge = openvm_execution_bridge.OpenVMExecutionBridgeEncoder()
        self.memory = openvm_memory.OpenVMMemoryEncoder()
        self.pc_lookup = openvm_pc_lookup.OpenVMPCLookupEncoder(basic_block)
        self.variable_range_checker = (
            openvm_variable_range_checker.OpenVMVariableRangeCheckerEncoder()
        )
        self.tuple_range_checker = (
            openvm_tuple_range_checker.OpenVMTupleRangeCheckerEncoder()
        )

        super().__init__(cur_state)
        self.matchers = []
    
    def __match_execution_bridge(self, defid: int, data: Any):
        match data:
            case {
                "id": id,
                "mult": mult,
                "args": [pc, timestamp],
            } if id == defid:
                self.execution_bridge.add(mult, pc, timestamp)
                return True
            case _:
                return False
    
    def __match_memory(self, defid: int, data: Any):
        match data:
            case {
                "id": id,
                "mult": mult,
                "args": [address_space, pointer, *data, timestamp],
            } if id == defid:
                self.memory.add(mult, address_space, pointer, data, timestamp)
                return True
            case _:
                return False
    
    def __match_pc_lookup(self, defid: int, data: Any):
        match data:
            case {
                "id": id,
                "mult": mult,
                "args": [pc, op, a, b, c, d, e, f, g],
            } if id == defid:
                self.pc_lookup.add(mult, pc, op, a, b, c, d, e, f, g)
                return True
            case _:
                return False

    def __match_variable_range_checker(self, defid: int, data: Any):
        match data:
            case {
                "id": id,
                "mult": mult,
                "args": [x, bits],
            } if id == defid:
                self.variable_range_checker.add(mult, x, bits)
                return True
            case _:
                return False

    def __match_bitwise_lookup(self, defid: int, data: Any):
        match data:
            case {
                "id": id,
                "mult": mult,
                "args": [x, y, z, op],
            } if id == defid:
                self.bitwise_lookup.add(mult, x, y, z, op)
                return True
            case _:
                return False

    def __match_tuple_range_checker(self, defid: int, data: Any):
        match data:
            case {
                "id": id,
                "mult": mult,
                "args": [x, y],
            } if id == defid:
                self.tuple_range_checker.add(mult, x, y)
                return True
            case _:
                return False

    def configure_from_bus_ids(self, bus_ids: dict[str, Any]):
        for id,data in bus_ids.items():
            id = int(id)
            match data:
                case "ExecutionBridge":
                    self.add_encoder(self.execution_bridge)
                    self.matchers.append(lambda data, id=id: self.__match_execution_bridge(id, data))
                case "Memory":
                    self.add_encoder(self.memory)
                    self.matchers.append(lambda data, id=id: self.__match_memory(id, data))
                case "PcLookup":
                    self.add_encoder(self.pc_lookup)
                    self.matchers.append(lambda data, id=id: self.__match_pc_lookup(id, data))
                case {"Other": "VariableRangeChecker"}:
                    self.add_encoder(self.variable_range_checker)
                    self.matchers.append(lambda data, id=id: self.__match_variable_range_checker(id, data))
                case {"Other": "BitwiseLookup"}:
                    self.add_encoder(self.bitwise_lookup)
                    self.matchers.append(lambda data, id=id: self.__match_bitwise_lookup(id, data))
                case {"Other": {"TupleRangeChecker": [max0, max1]}}:
                    self.tuple_range_checker.MAX_0 = max0
                    self.tuple_range_checker.MAX_1 = max1
                    self.matchers.append(lambda data, id=id: self.__match_tuple_range_checker(id, data))
                case _:
                    logging.error(f"Unsupported bus definition: {id} -> {data}")

    def add(self, data: Any):
        """Pattern-match a raw bus interaction record and forward it to the right encoder."""
        for matcher in self.matchers:
            if matcher(data):
                return
        logging.error(f"Unsupported bus interaction: {data}")
