"""Abstract base for one OpenVM bus: collect interactions, emit constraints and I/O maps."""
import collections
from ..smt.utils import *

BusInteraction = collections.namedtuple("BusInteraction", ["mult", "args"])


class SingleInteractionEncoder:
    """
    Base class for an encoder of a single bus. The `name` should be used for
    variables names to disambiguate them when multiple constraint systems are
    combined.
    An encoder should implement an `encode` method that encodes a single
    interaction with the proper arguments it expects.

    The general contract is:

    * first call `add` for each interaction
    * then call `encode_pointwise` for each interaction
    * then call `encode_all`
    * then call `get_axioms`
    * then call `get_globals`, `build_io_relation`, `get_auxiliaries`
    """

    _interactions: list[BusInteraction]
    # name of the bus, used for comments and variable names
    NAME: str
    # whether the last data is a timestamp, used by the visualizer
    TIMESTAMPED: bool = False
    # whether the bus is stateful
    STATEFUL: bool = False

    def __init__(self):
        """Initialize an empty interaction buffer for this bus."""
        self._interactions = []

    def constraints(self) -> list[FNode]:
        """Return the current global constraint list from the owning converter state."""
        return self._cur_state.constraints

    def solver(self) -> Solver:
        """Return the incremental solver used by the owning converter state (if any)."""
        return self._cur_state.constraint_solver
    
    def _symbol(self, name: str, sort, **kwargs) -> FNode:
        return self._cur_state._symbol(name, sort, **kwargs)

    @staticmethod
    def _wrap_field(x: Any) -> Any:
        """Reduce every field (Int) leaf modulo P so stored interactions hold
        canonical field elements. Every bus-interaction argument is a field
        value, so a leaf is asserted to be Int. Constants fold to their
        canonical representative in [0,P) (keeping ``is_int_constant``);
        non-constants are wrapped as ``(x mod P)``. List/tuple structure (e.g. a
        memory interaction's data limbs) is preserved. Consumers can then
        compare stored args with a plain ``Equals``/``LT`` — no per-use
        ``wrap_mod`` needed."""
        if isinstance(x, (list, tuple)):
            return [SingleInteractionEncoder._wrap_field(e) for e in x]
        assert x.get_type().is_int_type(), f"bus interaction field must be Int, got {x.get_type()}: {x}"
        folded = x.simplify()
        if folded.is_int_constant():
            return Int(folded.constant_value() % ARGS().field_type.value)
        return wrap_mod(x)

    def add(self, mult: FNode, *args: Any) -> FNode:
        """Add a single interaction, storing all field values reduced mod P."""
        #if self.solver().check_is_valid(Equals(mult, Int(0))):
        #    logging.debug("dropping interaction with mult = 0")
        #    return
        self._interactions.append(
            BusInteraction(self._wrap_field(mult), tuple(self._wrap_field(a) for a in args))
        )
    
    def encode_all(self) -> Iterable[FNode]:
        """Encode the relationships between the bus interactions."""
        return None

    def encode(self) -> Iterable[FNode]:
        """Encode all buffered interactions by calling `encode` for each one (if provided)."""
        if hasattr(self, "encode_pointwise"):
            for bi in self._interactions:
                yield with_comment(
                    self.encode_pointwise(bi.mult, *bi.args),
                    f"{self.NAME} {bi.args}"
                )
        yield from (self.encode_all() or [])

    def get_axioms(self) -> Iterable[FNode]:
        """Returns the axioms generated by the encoder."""
        return
        yield

    def consequences(self) -> Iterable[FNode]:
        """Statements *derived from* this encoder's constraints (as opposed to
        constraints the circuit commits to).

        These are added to the encoding as premises for the reference (before)
        program only, never as proof obligations for the checked (after)
        program — see ``verifier.encoding()``. Populated by ``encode`` runs
        that stash derived facts on ``self._consequences``. Default: none."""
        yield from getattr(self, "_consequences", [])

    def get_globals(self) -> frozenset[FNode]:
        """Returns the global symbols that should not be part of any quantifier."""
        return getattr(self, "globals", frozenset())

    def get_interpreters(self) -> dict:
        """Return interpreters for the UFs used by the encoder."""
        return getattr(self, "interpreters", {})

    def _io_equals(self, x: FNode, y: FNode) -> FNode:
        if x.get_type().is_int_type() and y.get_type().is_int_type():
            return Equals(wrap_mod(Minus(x, y)), Int(0))
        return Equals(x, y)

    def build_io_relation(
        self, other: "SingleInteractionEncoder"
    ) -> tuple[FNode, frozenset[FNode]]:
        """Equate this encoder's input and output summaries with ``other`` (symbol-wise)."""
        parts: list[FNode] = []
        for attr, lab in (("inputs", "INPUT"), ("outputs", "OUTPUT")):
            a = getattr(self, attr, ())
            b = getattr(other, attr, ())
            if not a or not b:
                continue
            parts.append(
                with_comment(
                    And(self._io_equals(x, y) for x, y in zip(a, b, strict=True)),
                    f"{lab} RELATION for {self.NAME}",
                )
            )
        if not parts:
            return (TRUE(), frozenset())
        return (And(*parts), frozenset())

    def get_auxiliaries(self) -> dict:
        """Return auxiliary symbols introduced by this encoder (defaults to empty)."""
        s = getattr(self, "auxiliaries", frozenset())
        return {self.NAME: s} if len(s) > 0 else {}