import collections
from ..smt.utils import *

BusInteraction = collections.namedtuple("BusInteraction", ["mult", "args"])


class SingleInteractionEncoder:
    """
    Base class for an encoder of a single bus. The `name` should be used for
    variables names to disambiguate them when multiple constraint systems are
    combined.
    An encoder should implement an `encode` method that encodes a single
    interaction with the proper arguments it expects.

    The general contract is:

    * first call `add` for each interaction
    * then call `encode_pointwise` for each interaction
    * then call `encode_all`
    * then call `get_axioms`
    * then call `get_globals`, `get_inputs`, `get_outputs`, `get_auxiliaries`
    """

    _interactions: list[BusInteraction]
    NAME: str

    def __init__(self):
        """Initialize an empty interaction buffer for this bus."""
        self._interactions = []

    def constraints(self) -> list[FNode]:
        """Return the current global constraint list from the owning converter state."""
        return self._cur_state.constraints

    def solver(self) -> Solver:
        """Return the incremental solver used by the owning converter state (if any)."""
        return self._cur_state.constraint_solver
    
    def _symbol(self, name: str, sort) -> FNode:
        return self._cur_state._symbol(name, sort)

    @simple_profile
    def add(self, mult: FNode, *args: Any) -> FNode:
        """Add a single interaction (skipping it if `mult` is provably zero)."""
        #if self.solver().check_is_valid(Equals(mult, Int(0))):
        #    logging.debug("dropping interaction with mult = 0")
        #    return
        self._interactions.append(BusInteraction(mult, args))
    
    def encode_all(self) -> Iterable[FNode]:
        """Encode the relationships between the bus interactions."""
        return []

    def encode(self) -> Iterable[FNode]:
        """Encode all buffered interactions by calling `encode` for each one (if provided)."""
        if hasattr(self, "encode_pointwise"):
            for bi in self._interactions:
                yield with_comment(
                    self.encode_pointwise(bi.mult, *bi.args),
                    f"{self.NAME} {bi.args}"
                )
        yield from self.encode_all()

    def get_axioms(self) -> Iterable[FNode]:
        """Returns the axioms generated by the encoder."""
        return
        yield

    def get_globals(self) -> frozenset[FNode]:
        """Returns the global symbols that should not be part of any quantifier."""
        return getattr(self, "globals", frozenset())

    def get_interpreters(self) -> dict:
        """Return interpreters for the UFs used by the encoder."""
        return getattr(self, "interpreters", {})

    def get_inputs(self) -> dict:
        """Return per-bus input symbols (if the encoder exposes them)."""
        s = getattr(self, "inputs", frozenset())
        return {self.NAME: s} if len(s) > 0 else {}

    def get_outputs(self) -> dict:
        """Return per-bus output symbols (if the encoder exposes them)."""
        s = getattr(self, "outputs", frozenset())
        return {self.NAME: s} if len(s) > 0 else {}

    def get_auxiliaries(self) -> dict:
        """Return auxiliary symbols introduced by this encoder (defaults to empty)."""
        s = getattr(self, "auxiliaries", frozenset())
        return {self.NAME: s} if len(s) > 0 else {}