import collections
from ..smt.utils import *

BusInteraction = collections.namedtuple('BusInteraction', ['mult', 'args'])

class SingleInteractionEncoder:
    """
    Base class for an encoder of a single bus. The `name` should be used for
    variables names to disambiguate them when multiple constraint systems are
    combined.
    An encoder should impklement an `encode` method that encodes a single
    interaction with the proper arguments it expects.

    The general contract is:
    
    * first call `add` for every interaction
    * then call `encode_all`
    * then call `get_axioms` and `get_globals`
    """

    _interactions: list[BusInteraction]

    def __init__(self):
        self._interactions = []
    
    def constraints(self) -> list[FNode]:
        return self._cur_state.constraints
    
    def solver(self) -> Solver:
        return self._cur_state.constraint_solver
    
    @simple_profile
    def add(self, mult: FNode, *args: Any) -> FNode:
        if self.solver() is not None and self.solver().is_valid(Equals(mult, Int(0))):
            logging.debug("dropping interaction with mult = 0")
            return
        self._interactions.append(BusInteraction(mult, args))

    def get_axioms(self) -> list[FNode]:
        """Returns the axioms generated by the encoder."""
        return None
    
    def get_globals(self) -> frozenset[FNode]:
        """Returns the global symbols that should not be part of any quantifier."""
        return getattr(self, 'globals', frozenset())

    def encode_all(self) -> Iterable[FNode]:
        if hasattr(self, 'encode'):
            return (self.encode(bi.mult, *bi.args) for bi in self._interactions)
        return []
    
    def get_inputs(self) -> dict:
        return {}
    
    def get_outputs(self) -> dict:
        return {}
    
    def get_auxiliaries(self) -> dict:
        return getattr(self, 'auxiliaries', frozenset())